name: Changelog CI
on: [pull_request]

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v0.7.0
        with:
          committer_email: dothq-robot@users.noreply.github.com
        env:
          # optional, only required for ``private`` repositories
          # and required if the changelog comment
          # option is turned on through the config file
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
