name: CI
on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install...
        run: yarn

      - name: Format...
        run: yarn prettier

      - name: Upload changes...
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'dothq-robot'
          author_email: '72629236+dothq-robot@users.noreply.github.com'
          message: '🎨 Enforce code style'
