name: CI
on: [push, pull_request]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install...
        run: yarn

      - name: Format...
        run: yarn prettier

      - name: Upload changes...
        run: |
          git config --global user.name "dothq-robot"
          git config --global user.email "72629236+dothq-robot@users.noreply.github.com"
          git status
          git add .
          git commit -m "🎨 Enforce code style"
          git push origin main
