name: TODO workflow
on: [push, pull_request]

jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run tdg-github-action
        uses: ribtoks/tdg-github-action@master
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install...
        run: yarn

      - name: Format...
        run: yarn prettier

      - name: Upload changes...
        uses: EndBug/add-and-commit@v7
        with:
          author_email: dothq-robot@users.noreply.github.com
          message: '🎨 Enforce code style'
