name: Prettier
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install...
        run: yarn

      - name: Test...
        run: yarn test

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install...
        run: yarn

      - name: Format...
        run: yarn prettier

      - name: Upload changes...
        uses: EndBug/add-and-commit@v7
        with:
          author_email: dothq-robot@users.noreply.github.com
          message: '🎨 Enforce code style'
